language: c
before_install:
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.7-linux64.tar.xz
  - tar xf arduino-1.8.7-linux64.tar.xz
  - sudo mv arduino-1.8.7 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

script:
  - arduino --verify --board arduino:avr:uno Backpack/Backpack.ino

notifications:
  email:
    on_success: always
    on_failure: always
